Finish mobile version
abubakar83/Portfolio pull request #2
Opened 2022-12-04 00:16 UTC by abubakar83

create branch

2022-12-04 01:07 UTC, emmiiorji requested changes
Hi @abubakar83, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/205468567-21532379-4571-4626-a864-2c0cc33e42ee.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow

## Required Changes ♻️

- You have mistakenly named your readme file as `redme.md` instead of `README.md`. Kindly correct this

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-04 01:07 UTC, emmiiorji commented on index.html
> +              </p>-->
In order to clean up the code base, kindly remove commented pieces of code.

2022-12-04 01:07 UTC, emmiiorji commented on index.html
> +              </p> -->
As pointed out above and for the same reasons, kindly remove commented pieces of code.

2022-12-04 01:07 UTC, emmiiorji commented on style.css
> +}
In order to match the design, kindly adjust the margin between the technology listings.

Your design:
![image](https://user-images.githubusercontent.com/20554583/205468775-b73892c8-b89d-4dea-9972-d8bdf0f3f1a3.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/205468793-d5a9cba9-be21-4020-9c5d-e454fd5c568a.png)

2022-12-04 01:07 UTC, emmiiorji commented on style.css
> +}
You have done great implementing the button interactions. However, when I click on a button, the color does not change after releasing the click but only returns to normal on the click outside of the button. Kindly work on this, I believe you can fix it.

Also, to make it match the design, kindly remove the black borders.

Color on click that does not change on click release:
![image](https://user-images.githubusercontent.com/20554583/205468987-7507e2f2-33d0-4925-a5d8-8c60c160894b.png)

Figma button interactions:
![image](https://user-images.githubusercontent.com/20554583/205469042-145ed422-865d-4389-8ccd-81b719aeb88b.png)

2022-12-04 01:13 UTC, abubakar83 commented on index.html
> +              </p>-->
ok

2022-12-04 01:32 UTC, abubakar83 commented on style.css
> +}
HI @emmiiorji  I did my work that you said me

2022-12-04 02:21 UTC, emmiiorji requested changes
Hi @abubakar83, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![little-bit-small](https://user-images.githubusercontent.com/20554583/205470885-c9b63e92-5532-4ea0-ae1f-606b8418ea7b.gif)

## Good Highlights✔️

- Linter checks are passing
- Some requested changes have been implemented


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-04 02:21 UTC, emmiiorji commented on style.css
> +  border-style: none;
As earlier mentioned, when I click on a button, the color does not change after releasing the click but only returns to normal on the click outside of the button.

Here's an illustration for that:

https://user-images.githubusercontent.com/20554583/205470707-11582147-dcb2-43ee-b4b6-992d8f27e775.mp4

2022-12-04 02:21 UTC, emmiiorji commented on style.css
> +}
As requested earlier kindly add some margin between the technologies cards.

Your design:
![image](https://user-images.githubusercontent.com/20554583/205470834-ad651c49-cb60-429d-9304-64a918feff65.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/205470835-49377f14-f98e-4065-b6b5-c294c21b626b.png)

2022-12-08 19:29 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @abubakar83 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark: 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

_Check the comment under this block_

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 19:29 UTC, iambenkis commented on README.md
> +
- [ ] Great job creating the documentation of your project :+1: , To make it more professional, it could be better if you provide a link that is working on the `MIT` licence :+1:

2022-12-08 19:29 UTC, iambenkis commented on index.html
> +                            </ul>
- [ ] Great job improving this part here :+1: . However , I've noticed that it show differently in many mobile screens. You are supposed to make it responsible in all the mobile screens. Kindly improve that.

Your design 
![Screenshot from 2022-12-08 21-04-45](https://user-images.githubusercontent.com/80458199/206547561-4e8424de-8073-42ad-aa0e-04d765e2358c.png)

Figma design

![Screenshot from 2022-12-08 21-15-33](https://user-images.githubusercontent.com/80458199/206547553-cf48018d-7b88-4ddd-bcc3-9bf0ca5b347a.png)

2022-12-08 21:11 UTC, abubakar83 commented on index.html
> +                            </ul>
ok

2022-12-08 21:48 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @abubakar83 ,  

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- mobile design ok
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 21:54 UTC, merged